spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092  #default port no
      group-id: sb-group
  mail:
    host: smtp.gmail.com
    password: "gmail app password"
    username: "springboot3-microservices@gmail.com"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    username: root
    password: ${DB_PWD}
    url: jdbc:mysql://localhost:3306/${DATABASE}
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        bytecode:
          use_reflection_optimizer: false
        provider: org.hibernate.bytecode.internal.none.None
        generate_statistics: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: springboot3-microservices
logging:
  level:
    org:
      springframework: DEBUG
      hibernate:
        stat: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*, openapi, swagger-ui'
      base-path: /management
server:
  port: 8081
  servlet:
    contextPath: /springboot3-microservices
springdoc:
  show-actuator: true
  swagger-ui:
    path: /documentation
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true
  group-configs:
    - group: Testing APIs
      paths-to-match: /test/**
    - group: Admin Management
      paths-to-match: /management/**
    - group: Animal APIs
      paths-to-match: /pet/**
    - group: Kafka APIs
      paths-to-match: /kafka/**

application:
  auth:
    roles:
      USER:
        username: ${USER_USERNAME}
        password: ${USER_PWD}
      ADMIN:
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PWD}
  twilio:
    accountSid: ${ACCOUNT_SID}
    authToken: ${AUTH_TOKEN}
    phoneNumber: ${PHONE_NUMBER}

#http://localhost:8081/springboot3-microservices/documentation
#http://localhost:8081/springboot3-microservices/swagger-ui/index.html